# Convertions

Here we will present some built in functions that convert the data to other formats.

In [5]:
from hera import GIS
from shapely.geometry import Polygon
import matplotlib.pyplot as plt

converter = GIS.utils.STL.convert(projectName = "Example", FilesDirectory = "/home/ofir/tmp/BNTL-HAIFA")

## Convertion to stl

The data can be converted from a geodataframe format to an stl format using a buit in convertion function.
The data can be induced as a geodataframe or as a name of a saved polygon in the database.
If the data is a dataframe, the whole dataframe is converted to stl.
If it is a polygon, a dataframe that contains only the requested polygon is being made and then converted to stl.

The stl string is saved by default as a file and the path to the file is added to the database.
The path is by default the FilesDirectory, but other paths may be given.
Any parameters and corresponding values may be given to the function too, and they are induced to the new metadata document.

A name for the new file must be given even if the file is not saved, because it is used in the stl string.

The size of cells in the dataframe used for the convention is 50X50 meters by default. 
It can be changed by inducing another value as the parameter dxdy.

In the next example the file is not saved. We would create an stl string for a polygon that holds part of Haifa.

In [7]:
polyon = "PartOfHaifa"
NewFileName = "PartOfHaifaSTL"

stlstring, data = converter.toSTL(data=polyon, NewFileName=NewFileName, save=False, dxdy=100)

Mesh boundaries x=(196002.55982653957,200000.0) ; y=(745000.0,749125.2014938995)

The function returns a the stl string and a dataframe that holds the x and y coordinates and their hieghts.
It also holds the max values of the x, y and z axis.

In [8]:
data

,XY,Height,gridxMin,gridxMax,gridy,gridyMax,gridz,gridzMax
0,"(200000.0, 747748.2033010876)",0,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
1,"(199998.81142653956, 747749.7777938995)",0,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
2,"(199993.17612653956, 747751.0301938995)",0,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
3,"(199992.31822653956, 747751.5335938995)",0,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
4,"(199990.61652653955, 747753.6088938995)",0,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
...,...,...,...,...,...,...,...,...
48551,"(199314.94922653955, 745370.0972938995)",290,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
48552,"(199319.28222653957, 745370.6332938995)",290,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
48553,"(199329.44942653956, 745371.1836938995)",290,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
48554,"(199332.87052653957, 745372.0846938995)",290,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467
48555,"(199333.83292653956, 745375.9999938995)",290,196002.559827,199902.559827,745000.0,749100.0,-3.19172,301.204467